[tool.poetry]
name = "bottle-time"
version = "0.1.0"
description = ""
authors = ["John Eckhart <jeckhart@hey.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
circuitpython-stubs = "^9.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
